name: MY FIRST GITHUB ACTION

on:
  push:
    branches:
      - master

env:
  NAME: "ABDUSALAM FATAI"
  PROFESSION: "Devop Enthusiast"
  PASSION: "DEVOPS ENGINEERING"

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Echo Github Actions
        run:  echo "Hi, this is $NAME. I am a $PROFESSION & $PASSION is my passion"
  post-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "echo postbuilds steps"
        run: echo "POSTBUILDS STEPS AFTER EXECUTION OF ABOVE STEPS"
